name: Update GitHub Pages

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - uses: actions/setup-python@v4
      with:
        python-version: '2.7.17'
    - uses: actions/checkout@v1
    - uses: enriikke/gatsby-gh-pages-action@v2
      with:
        access-token: ${{ secrets.ACCESS_TOKEN }}
        deploy-branch: gh-pages