name: Update GitHub Pages

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        npm ci
        npm run build
    - name: Deploy to GitHub Pages
      run: |
        npm run deploy